include $(GOROOT)/src/Make.inc

TARG=net/facebook

GOFILES=graph.go\
user.go\
page.go\
picture.go\
education.go\
work.go\
friends.go\
home.go\
paging.go\
comment.go\
news.go\
feed.go\
privacy.go\
data.go

include $(GOROOT)/src/Make.pkg