include $(GOROOT)/src/Make.inc

TARG=net/facebook

GOFILES=graph.go\
user.go\
page.go\
picture.go\
education.go\
work.go\
friends.go\
paging.go\
comment.go\
privacy.go\
post.go\
group.go\
venue.go\
event.go\
invitation.go\
application.go\
tools.go\
photo.go\
insights.go\
note.go\
subscription.go\
statusmessage.go\
video.go\
album.go\
link.go\
checkin.go

include $(GOROOT)/src/Make.pkg