include $(GOROOT)/src/Make.inc

TARG=github.com/Agon/go-facebook/facebook

GOFILES=response.go\
graph.go\
user.go\
work.go\
object.go\
page.go\
education.go\
album.go\
metadata.go

include $(GOROOT)/src/Make.pkg